import React from 'react'
import "./servicesservice.css"
import ServicesServiceItem from './ServicesServiceItem/ServicesServiceItem'

function ServicesService() {
    return (
        <section className='services-service'>
            <ul className='services-service-list'>
                <ServicesServiceItem data={{name: "Project Plan", text: "There are many variations of the passages of lorem Ipsum from available, majority.", itemData:{detailsData:{title: "We set the trends of modern living Services.", titleH3: "It is a long established fact that a reader will be distracted by the of readable content of a page", text:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine.", textSecond:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine"}, videoData:{link:"pLTAc2HyXCM"}}}} key={"Project Plan"}/>
                <ServicesServiceItem data={{name: "Interior Work", text: "There are many variations of the passages of lorem Ipsum from available, majority.", itemData:{detailsData:{title: "We set the trends of modern living Services.", titleH3: "It is a long established fact that a reader will be distracted by the of readable content of a page", text:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine.", textSecond:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine"}, videoData:{link:"pLTAc2HyXCM"}}}} key={"Interior Work"}/>
                <ServicesServiceItem data={{name: "Retail Design", text: "There are many variations of the passages of lorem Ipsum from available, majority.", itemData:{detailsData:{title: "We set the trends of modern living Services.", titleH3: "It is a long established fact that a reader will be distracted by the of readable content of a page", text:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine.", textSecond:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine"}, videoData:{link:"pLTAc2HyXCM"}}}} key={"Retail Design"}/>
                <ServicesServiceItem data={{name: "2d/3d Art Work", text: "There are many variations of the passages of lorem Ipsum from available, majority.", itemData:{detailsData:{title: "We set the trends of modern living Services.", titleH3: "It is a long established fact that a reader will be distracted by the of readable content of a page", text:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine.", textSecond:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine"}, videoData:{link:"pLTAc2HyXCM"}}}} key={"2d/3d Art Work"}/>
                <ServicesServiceItem data={{name: "Interior Work", text: "There are many variations of the passages of lorem Ipsum from available, majority.", itemData:{detailsData:{title: "We set the trends of modern living Services.", titleH3: "It is a long established fact that a reader will be distracted by the of readable content of a page", text:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine.", textSecond:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine"}, videoData:{link:"pLTAc2HyXCM"}}}} key={"Interior1 Work"}/>
                <ServicesServiceItem data={{name: "Decoration Work", text: "There are many variations of the passages of lorem Ipsum from available, majority.", itemData:{detailsData:{title: "We set the trends of modern living Services.", titleH3: "It is a long established fact that a reader will be distracted by the of readable content of a page", text:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine.", textSecond:"when lookings at its layouts the points spriof using that it has a more less normal.A wonderful serenity has taken pgossession of my entire soul, like thesce sweet morndsings of sphring which I enjoy with my forwhole heart. I am alone, and feel the charm of excgistence in this spot, which was created for the bliss of souls like mine"}, videoData:{link:"pLTAc2HyXCM"}}}} key={"Decoration Work"}/>
            </ul>
        </section>
    )
}

export default ServicesService
